### ISSUE TITLE
Can send email

### ISSUE THREAD

**Issue by yothinix** [yothinix/mssum#2]
### Exit Criteria
- [ ] can send email via sendgrid

### Task
- [ ] Create Email template based on Issue / Milestone data
- [ ] Can send email to recipent
