### ISSUE TITLE
Can pull issues from github

### ISSUE THREAD

**Issue by yothinix** [yothinix/mssum#3]
### Exit Criteria
- [x] Can pull issue from GitHub

### Task
- [x] Can pull issue from GitHub repository
- [x] BONUS: Can pull only issues relevant to milestone
